### ISSUE TITLE
data extraction for point time series for large number of points

### ISSUE THREAD

**Issue by sshoaie** [vandersat/vds-api-client#10]
I have the following code:

```python
from vds_api_client import VdsApiV2

vds = VdsApiV2('sample@vandersat.com', 'password')

# Latitude list extracted from the .csv file
lat_list = [43.90623]
# Longitude list extracted from the .csv file
lon_list = [-94.40173]

vds.set_outfold('testdata/csv')  # Created if it does not exist
# Define the date range and average window.
vds.gen_time_series_requests(products=['SM-AMSR2-XN-DESC_V003_100'],
                             start_time='2012-07-24', end_time='2020-02-03',
                             lons=lon_list, lats=lat_list, av_win=10, clim=True)

# When requests are already made, they will not be resubmitted.
if not vds.uuids:
    vds.submit_async_requests()

vds.download_async_files()
```

Question: if the ```python lat_list``` and ```python lon_list``` variables are increased up to 500 points, is this then calculated in parallel, if so, to what extent? And what is the expected waiting time? One source informed me that for 150 points the time series extraction took 48H. I expect that they used the date range that is given in the code; since 2012.

**Comment by teije01** [comment]
The jobs are submitted simultaneously. In the background are 75 workers available to process these requests in parallel. If there are no requests pending, this should take around 20 minutes or so. Otherwise you might have to wait indeed. Though 48 hours seems dis proportionally long, and is generally not accurate in my experience

**Comment by sshoaie** [comment]
Thanks!

I just got confirmation that the latitude and longitude points were used as single pairs in stead of using them as a batch - so one by one computation. The user has been notified of this feature and should extract data at a quicker rate.
