### ISSUE TITLE
Make downloading of parallel point time series explicit in the documentation

### ISSUE THREAD

**Issue by cpaulik** [vandersat/vds-api-client#11]
We had some issues with people using a loop over `vds.gen_time_series_requests` instead of giving a list of `lons` and `lats`.

We should improve the documentation to make the usage pattern clearer when downloading multiple point time series.

@sshoaie Maybe that would be something for you since you had the contact with the customer and know where the miscommunication happened?

**Comment by teije01** [comment]
The docstring already states:

```python
"""
***
lats: list of float
    list of latitude values
lons: list or float
    list of longitude values
***
"""
```

But maybe we can state somewhere that all requests generated before vds.submit_async_requests() are processed in parallel.

**Comment by sshoaie** [comment]
I tried to assign myself to this and labels / due date, can you verify if I have the appropriate rights to do so? Then I can put it on the agenda.

**Comment by teije01** [comment]
I assigned you to this issue, but we don't have labels implemented here like in gitlab. You don't need to plan it on this platform, but you can do so in your own agenda if you will. Please open a pull request or discuss for necessary changes
