### ISSUE TITLE
Automatically upload new releases to PyPI

### ISSUE THREAD

**Issue by ajgeers** [vandersat/vds-api-client#3]

**Comment by teije01** [comment]
I actually think that automatic upload to pypi is sufficient since the documentation is rendered directly from the README.rst. Maybe we could change this issue to reflect that?

**Comment by teije01** [comment]
I added a github workflow to [deploy to pypi](https://github.com/vandersat/vds-api-client/commit/c1176a9266470e382057efae737a2851e400043d). Hope it's set-up correctly, up to test it soon

**Comment by teije01** [comment]
Now also added a pypi badge to the documentation. Really fancy if you ask me. Please let me know if we need more

**Comment by ajgeers** [comment]
Nice solution

> Maybe we could change this issue to reflect that?

Yes, I updated the issue title
