### ISSUE TITLE
rois filter function is not working with description regex

### ISSUE THREAD

**Issue by mvanklink** [vandersat/vds-api-client#37]
The rois.filter method is not working on description regex:

```
vds = VdsApiV2(vds_user, vds_password)
vds.rois.filter(name_regex='test') --> WORK
vds.rois.filter(description_regex='test') --> Return an error
```

Error message

```
Traceback (most recent call last):
  File "/usr/share/pycharm/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/marcc/anaconda3/envs/shape_data_retrieval/lib/python3.8/site-packages/vds_api_client/types.py", line 217, in filter
    elif dre is not None and not dre.search(roi.description):
TypeError: expected string or bytes-like object
```

**Comment by teije01** [comment]
For which account does this error occur?

**Comment by mvanklink** [comment]
@teije01 To come back on your comment in the Infrastructure channel: When regular expression `dre` is `None` it is handled, not when `roi.description` is `None`

**Comment by mchautems** [comment]
It is when using the insurance account, the bug only occurs with the description regex; the name regex work perfectly

**Comment by teije01** [comment]
As @mvanklink indicated, this is because the description can return `None` instead of a string. In that case we should not apply the filter here. For now you can either add descriptions to all your rois, or you have to make sure that the filter ignores None type descriptions. This fix will be postponed until after some of our deadlines (but you are welcome to give it a try)

**Comment by sshoaie** [comment]
I managed to resole this by implementing the following (in the vds_api_client/types.py script, in the `filter` method of the `Rois` class):

```python
            elif dre is not None and not dre.search(roi.description):
                continue
            else:
```

to

```python
            elif dre is not None and not dre.search(str(roi.description)):
                continue
            else:
```

This solution of mine is just based on some trial and error and it resolved my issue.

**Comment by teije01** [comment]
I've added a roi to the test account without a description so the test should now fail in it's current state. I'm perfectly fine with this solution. Could you open a pull request?

**Comment by sshoaie** [comment]
I opened a pull request here: #43

**Comment by teije01** [comment]
This was added to the latest [release v2.1.2](https://github.com/vandersat/vds-api-client/releases/tag/v2.1.2) so you can update your packages now
