### ISSUE TITLE
Add option to add/update the description associated with ROIs

### ISSUE THREAD

**Issue by sshoaie** [vandersat/vds-api-client#5]
In some cases the name_regex is not sufficient to distinguish between unique ROIs. In this instance the description can be used to provide less ambiguity. 

It would be very handy to have a selection of filtered rois that can be updated with a specific description (after they have already been created). Something like this:

```python
vds.rois.filter(name_regex='NAME').update_description('test shapes only')
```

**Comment by teije01** [comment]
Depends on PR #14

**Comment by teije01** [comment]
I have started on this issue, but the syntax will be slightly different as I don't like to bulk update descriptions. The following will approximate the new behaviour:

```python
vds.rois[25120].update(description='test shapes only')
```

If you want to do this for a selection, you can always run the following:
```python
for roi in vds.rois.filter(name_regex='NAME'):
    roi.update(description='test shapes only')
```

**Comment by sshoaie** [comment]
The proposed solution seems good.
