### ISSUE TITLE
m2 instead of ha

### ISSUE THREAD

**Issue by guyon-planet** [vandersat/vds-api-client#51]
https://github.com/vandersat/vds-api-client/blob/008fba54f8d19893505eaa5d4248fa5fb7342fc5/vds_api_client/types.py#L232

**Comment by ajgeers** [comment]
Related to https://github.com/vandersat/vds-api-client/pull/48. `roi.area` returns the area in m^2. It is converted into hectares by dividing the amount of m^2 by 1e4.
